### ISSUE TITLE
Почему Sql? ORM нам даёт как раз абстрагироваться от базы. Тем более репозиторий уже не работает с SQL

### ISSUE THREAD

**Issue by ReactiveTurtle** [Far4ich/15.07_TL_Dz#1]
https://github.com/Far4ich/15.07_TL_Dz/blob/faeb9f2b8236a80e1e09730bb279ce86c0cd69a9/MedicineApi/Infrastructure/Data/PatientModel/SqlPatientRepository.cs#L8

**Comment by Far4ich** [comment]
Забыл переименовать когда переносил с sql
